package com.simsservice.model;

// default package
// Generated Mar 15, 2017 1:02:50 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class UserModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2833920844942689080L;
	private Integer userId;
	private String userType;
	private String firstName;
	private String lastName;
	private String email;
	private String loginId;
	private String password;
	private String status;
	private String addedBy;
	private Date addedDate;
	private String modifiedBy;
	private Date modifiedDate;

	public UserModel() {
	}

	public UserModel(String userType, String firstName, String lastName, String email, String loginId, String password,
			Date addedDate, Date modifiedDate) {
		this.userType = userType;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.loginId = loginId;
		this.password = password;
		this.addedDate = addedDate;
		this.modifiedDate = modifiedDate;
	}

	public UserModel(String userType, String firstName, String lastName, String email, String loginId, String password,
			String status, String addedBy, Date addedDate, String modifiedBy, Date modifiedDate) {
		this.userType = userType;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.loginId = loginId;
		this.password = password;
		this.status = status;
		this.addedBy = addedBy;
		this.addedDate = addedDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getAddedBy() {
		return this.addedBy;
	}

	public void setAddedBy(String addedBy) {
		this.addedBy = addedBy;
	}

	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
